config/routes.rb
Rails.application.routes.draw do
  root 'root#root'

  resources :users
  resource :session

  namespace :api do # , defaults: { format: :json }
    resources :topics
    resources :puns
    resources :likes
    get 'search', to: 'search#search'
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  handle          :string           not null
#  name            :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password
  validates :handle, :email, :session_token, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, length: { minimum: 8, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :likes
  has_many :liked_topics, through: :likes, source: :likeable, source_type: "Topic"
  has_many :puns
  has_many :ratings

  def self.find_by_credentials(handle, password)
    user = User.find_by(handle: handle)
    return nil unless user && user.is_password?(password)
    user
  end

  def self.top_20
    User
      .all
      .sort_by { |user| user.average_pun_rating }[0..19]
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    byebug
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def average_pun_rating
    rating = 0
    count = 0
    self.puns.each do |pun|
      unless pun.average_rating == -1
        rating += pun.average_rating
        count+=1
      end
    end
    count == 0 ? "n/a" : rating/count
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_signed_in, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if params[:confirm_password] != user_params[:password]
      flash.now[:errors] = ["Passwords do not match"]
      render :new
      return
    end

    if @user
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:handle, :password, :email, :name)
  end

end

app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">
  <%= form_auth %>

  <label for="name">Name</label>
  <input type="text" id="name" name="user[name]" value="<%= @user.name %>">

  <label for="email">Email</label>
  <input type="text" id="email" name="user[email]" value="<%= @user.email %>">

  <label for="handle">Username</label>
  <input type="text" id="handle" name="user[handle]" value="<%= @user.handle %>">

  <label for="password">Password</label>
  <input type="password" id="password" name="user[password]" value="">

  <label for="confirm-password">Confirm Password</label>
  <input type="password" id="confirm-password" name="confirm_password" value="">

  <button>Create User</button>
</form>

app/views/users/show.html.erb
<h1> <%= @user.handle %> </h1>